### ISSUE TITLE
Tree display of cohorts has numerous problems displaying the Nolan.4 hierarchy.

### ISSUE THREAD

**Issue by WValenti** [mathmednet/diverweb-issues#18]
1. There are dozens of simple subsets, but only one (1) is listed.
2. There are only 37 total resultSets shown and there are actually on the order of 60.
3. Some combined set operands have no names!

This is (still) too complex to give to AnnaLisa, so I'm going to recreate Nolan.4 one resultSet at a time while watching the tree display to see when it goes sideways.
![Screen Shot 2022-03-03 at 3 13 21 PM](https://user-images.githubusercontent.com/3909236/156645367-d387da26-42df-4d98-9efa-fc64a487bd90.png)
![Screen Shot 2022-03-03 at 3 13 06 PM](https://user-images.githubusercontent.com/3909236/156645369-2f19ea03-a2e5-471c-8306-11dfb14350f7.png)
![Screen Shot 2022-03-03 at 3 12 49 PM](https://user-images.githubusercontent.com/3909236/156645370-773d02f4-3238-4020-b165-d04c9d16e824.png)
![Screen Shot 2022-03-03 at 3 12 27 PM](https://user-images.githubusercontent.com/3909236/156645372-19cc1bef-d463-4a55-b865-41626e7e2528.png)
![Screen Shot 2022-03-03 at 3 12 08 PM](https://user-images.githubusercontent.com/3909236/156645373-f5c0ca26-45ef-4feb-b4cc-760d5810b18b.png)

**Comment by Viqsi** [comment]
Partially blocked by #19.

**Comment by WValenti** [comment]
The issue with missing Compound Set operand name & description is due to resultSetConstraints.constraintValue being used (as it should be parent name) instead of parentAId or parentBId. This is only a problem when transferring sets from the prototype to the webapp when the prototype has been used to rename parents. This needs to change in the code, but is not in any way urgent, as it will not affect results in the future.  I'm leaving this issue open until it is resolved.

**Comment by WValenti** [comment]
Note that the issue with not all subsets being listed STILL shows up, and is difficult to reproduce as it can be corrected by a simple webpage refresh.

**Comment by Viqsi** [comment]
After discussing with Digital Wave, @WValenti is going to be sending (possibly via attaching to this issue) an example of diverRPC's JSON output that causes the tree construction bug and Annalisa will be looking into it. That's really all that remains of this issue.

**Comment by WValenti** [comment]
I did the following with the localhost version of the DiverWeb app:

curl -c my.cookies --request POST http://localhost:5000/api/v0/login -H 'Content-Type: application/json' -d '{"username":"username goes here", "password":"password goes here"}'

curl -b my.cookies --request GET http://localhost:5000/api/v0/resultset/info | gzip >for_Annalisa.json.gz

...and attached the file
[for_Annalisa.json.gz](https://github.com/mathmednet/diverweb-issues/files/8227013/for_Annalisa.json.gz)

**Comment by iamtheluckyest** [comment]
@WValenti It looks to me like this breaks because on the last three items parent and parent_set are both null. The tree-parsing function expects only one root, i.e. All Individuals, which it sets when it sees a cohort without a parent. Are those last three supposed to have a parent and something just happened to that data point? Or do I need to adjust the function to handle multiple roots? Incidentally, that data set also has two "All individuals" cohorts, that are the same except they have different `resultsetid`s. That doesn't break the UI right now because the parents are determined by cohort name, but it would likely present a problem when I take a pass at updating the code to use the `parent_set` id field instead.

**Comment by iamtheluckyest** [comment]
I also just took a stab at updating the tree parser to use `parent_set` instead of `parent` and there's still an issue with "constraint_values" using the cohort names instead of ids - I can't look up the cohort by name in the tree when I start sorting/linking it by ids. Is there any chance you are planning on updating that to use ids instead? Otherwise I could build another hash table to store the names alongside the ids for easier lookup (this would assume names are always unique, which I think is the current assumption, but I don't know if that might change going forward).

**Comment by Viqsi** [comment]
> @WValenti It looks to me like this breaks because on the last three items parent and parent_set are both null. The tree-parsing function expects only one root, i.e. All Individuals, which it sets when it sees a cohort without a parent. Are those last three supposed to have a parent and something just happened to that data point? Or do I need to adjust the function to handle multiple roots? Incidentally, that data set also has two "All individuals" cohorts, that are the same except they have different `resultsetid`s. That doesn't break the UI right now because the parents are determined by cohort name, but it would likely present a problem when I take a pass at updating the code to use the `parent_set` id field instead.
Honestly, it would probably be safer to always assume resultset id 1 is the root. That's how it's supposed to operate, at any rate - that's the id for "- ALL individuals -". Everything descends from it.

Every other resultset is supposed to have a parent. If you're not seeing one at any given time, that's an error in the database (and should probably be reported as such).

**Comment by iamtheluckyest** [comment]
Ah, yes, I saw that `second_set` property but forgot about it by the time I went to update the tree parser. That's been updated now to use ids instead of names to sort the tree, and I updated the root to be the cohort with `resultsetid === 1`. These changes are included in commit d9aa6c0 and I think that resolves this issue from my end.

**Comment by Viqsi** [comment]
Turns out @WValenti and I had a mutual misunderstanding w/r/t how "id 1" is supposed to work, but if that assumption is in place then this is indeed fixed. So I intend to take it from there. (We're kind of hammering out the details on the backend, but once given the proper info the frontend works as expected, and if we have to change what's sent I intend to handle that myself). So, from Digital Wave's perspective at least, this should be considered done. (We have our own work to do, though!)
