### ISSUE TITLE
"is any of" constraint needs to allow multiple selections

### ISSUE THREAD

**Issue by WValenti** [mathmednet/diverweb-issues#4]
![Screen Shot 2022-02-24 at 9 08 55 AM](https://user-images.githubusercontent.com/3909236/155539569-2a1a2c96-9be4-4ae6-9f95-170142ca5c94.png)

**Comment by Viqsi** [comment]
It's seemingly designated as taking multiple values in diverWeb's dispatch table (assuming utils/constraints.js is intended as something like a dispatch table), so IDK what's up here. Definitely need Digital Wave input.

**Comment by Viqsi** [comment]
Turns out this is being done via having comma-separated values typed into the input box. So, some help text should probably be added.

**Comment by iamtheluckyest** [comment]
I have provided a way to supply help text here. This is the text we're proposing, but we think it would be great to use a real example rather than `"my, value"`. Do you have a real value I can use (preferably short)?
![image](https://user-images.githubusercontent.com/19640576/157751889-f089667a-8c4a-4bfb-ac70-18ba7242e968.png)

In case the image is too small, the help text currently reads

> Separate values with commas. If value includes a comma, wrap the value with quotes. For example: \"my, value\".

**Comment by Viqsi** [comment]
I'm thinking just put in "my, value" for now and we'll figure out what to put in for real around the same time we take care of all the Lorem Ipsum text.

**Comment by Viqsi** [comment]
Merged with mathmednet/diverweb@03f4a8f, appears to work (help text is certainly displayed). Since this was a user confusion situation, IMO if there's any issues with actually passing that info to diverRPC, that's a separate issue, so closing this one. Thanks!
